// Copyright (c) QosmosUI 2025.
// QosmosUI licenses this file to you under the MIT license.
// See the license here https://github.com/QosmosUI/QosmosUI/blob/main/LICENSE.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace QosmosUI.Icons.FlatColorIcons;

public class FcCloth : ComponentBase
{
    [Parameter]
    public string Title { get; set; } = string.Empty;

    [Parameter]
    public string Size { get; set; } = "1em";

    [Parameter]
    public string Stroke { get; set; } = "currentColor";

    [Parameter]
    public string Fill { get; set; } = "currentColor";

    [Parameter]
    public string StrokeWidth { get; set; } = "0";

    [Parameter]
    public string StrokeLinecap { get; set; } = "round";

    [Parameter]
    public string StrokeLinejoin { get; set; } = "round";

    [Parameter]
    public string ViewBox { get; set; } = "0 0 48 48";

    [Parameter(CaptureUnmatchedValues = true)]
    public IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "svg");
        builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
        builder.AddAttribute(2, "viewBox", ViewBox);
        builder.AddAttribute(3, "width", Size);
        builder.AddAttribute(4, "height", Size);
        builder.AddAttribute(5, "fill", Fill);
        builder.AddAttribute(6, "stroke", Stroke);
        builder.AddAttribute(7, "stroke-width", StrokeWidth);
        builder.AddAttribute(8, "stroke-linecap", StrokeLinecap);
        builder.AddAttribute(9, "stroke-linejoin", StrokeLinejoin);
        builder.AddMultipleAttributes(10, AdditionalAttributes);
        if (!string.IsNullOrEmpty(Title))
        {
            builder.OpenElement(11, "title");
            builder.AddContent(12, Title);
            builder.CloseElement();
        }
		builder.OpenElement(13, "path");
		builder.AddAttribute(14, "fill", "#FF5722");
		builder.AddAttribute(15, "d", "M6,10v28c0,2.2,1.8,4,4,4h28c2.2,0,4-1.8,4-4V10c0-2.2-1.8-4-4-4H10C7.8,6,6,7.8,6,10z");
		builder.CloseElement();
		builder.OpenElement(16, "g");
		builder.AddAttribute(17, "fill", "#BF360C");
		builder.OpenElement(18, "rect");
		builder.AddAttribute(19, "x", "6");
		builder.AddAttribute(20, "y", "35");
		builder.AddAttribute(21, "width", "36");
		builder.AddAttribute(22, "height", "2");
		builder.CloseElement();
		builder.OpenElement(23, "rect");
		builder.AddAttribute(24, "x", "6");
		builder.AddAttribute(25, "y", "31");
		builder.AddAttribute(26, "width", "36");
		builder.AddAttribute(27, "height", "2");
		builder.CloseElement();
		builder.OpenElement(28, "path");
		builder.AddAttribute(29, "d", "M6.1,39c0.2,0.8,0.6,1.5,1.2,2h33.2c0.6-0.5,1-1.2,1.2-2H6.1z");
		builder.CloseElement();
		builder.OpenElement(30, "path");
		builder.AddAttribute(31, "d", "M6.1,9h35.7c-0.2-0.8-0.6-1.5-1.2-2H7.4C6.8,7.5,6.3,8.2,6.1,9z");
		builder.CloseElement();
		builder.OpenElement(32, "rect");
		builder.AddAttribute(33, "x", "6");
		builder.AddAttribute(34, "y", "23");
		builder.AddAttribute(35, "width", "36");
		builder.AddAttribute(36, "height", "2");
		builder.CloseElement();
		builder.OpenElement(37, "rect");
		builder.AddAttribute(38, "x", "6");
		builder.AddAttribute(39, "y", "27");
		builder.AddAttribute(40, "width", "36");
		builder.AddAttribute(41, "height", "2");
		builder.CloseElement();
		builder.OpenElement(42, "rect");
		builder.AddAttribute(43, "x", "6");
		builder.AddAttribute(44, "y", "15");
		builder.AddAttribute(45, "width", "36");
		builder.AddAttribute(46, "height", "2");
		builder.CloseElement();
		builder.OpenElement(47, "rect");
		builder.AddAttribute(48, "x", "6");
		builder.AddAttribute(49, "y", "11");
		builder.AddAttribute(50, "width", "36");
		builder.AddAttribute(51, "height", "2");
		builder.CloseElement();
		builder.OpenElement(52, "rect");
		builder.AddAttribute(53, "x", "6");
		builder.AddAttribute(54, "y", "19");
		builder.AddAttribute(55, "width", "36");
		builder.AddAttribute(56, "height", "2");
		builder.CloseElement();
		builder.CloseElement();
		builder.OpenElement(57, "g");
		builder.AddAttribute(58, "fill", "#FF8A65");
		builder.OpenElement(59, "rect");
		builder.AddAttribute(60, "x", "27");
		builder.AddAttribute(61, "y", "6");
		builder.AddAttribute(62, "width", "2");
		builder.AddAttribute(63, "height", "5");
		builder.CloseElement();
		builder.OpenElement(64, "rect");
		builder.AddAttribute(65, "x", "27");
		builder.AddAttribute(66, "y", "13");
		builder.AddAttribute(67, "width", "2");
		builder.AddAttribute(68, "height", "6");
		builder.CloseElement();
		builder.OpenElement(69, "rect");
		builder.AddAttribute(70, "x", "27");
		builder.AddAttribute(71, "y", "29");
		builder.AddAttribute(72, "width", "2");
		builder.AddAttribute(73, "height", "6");
		builder.CloseElement();
		builder.OpenElement(74, "rect");
		builder.AddAttribute(75, "x", "31");
		builder.AddAttribute(76, "y", "6");
		builder.AddAttribute(77, "width", "2");
		builder.AddAttribute(78, "height", "1");
		builder.CloseElement();
		builder.OpenElement(79, "rect");
		builder.AddAttribute(80, "x", "19");
		builder.AddAttribute(81, "y", "29");
		builder.AddAttribute(82, "width", "2");
		builder.AddAttribute(83, "height", "6");
		builder.CloseElement();
		builder.OpenElement(84, "rect");
		builder.AddAttribute(85, "x", "31");
		builder.AddAttribute(86, "y", "9");
		builder.AddAttribute(87, "width", "2");
		builder.AddAttribute(88, "height", "6");
		builder.CloseElement();
		builder.OpenElement(89, "rect");
		builder.AddAttribute(90, "x", "23");
		builder.AddAttribute(91, "y", "6");
		builder.AddAttribute(92, "width", "2");
		builder.AddAttribute(93, "height", "1");
		builder.CloseElement();
		builder.OpenElement(94, "rect");
		builder.AddAttribute(95, "x", "23");
		builder.AddAttribute(96, "y", "25");
		builder.AddAttribute(97, "width", "2");
		builder.AddAttribute(98, "height", "6");
		builder.CloseElement();
		builder.OpenElement(99, "rect");
		builder.AddAttribute(100, "x", "23");
		builder.AddAttribute(101, "y", "9");
		builder.AddAttribute(102, "width", "2");
		builder.AddAttribute(103, "height", "6");
		builder.CloseElement();
		builder.OpenElement(104, "rect");
		builder.AddAttribute(105, "x", "19");
		builder.AddAttribute(106, "y", "21");
		builder.AddAttribute(107, "width", "2");
		builder.AddAttribute(108, "height", "6");
		builder.CloseElement();
		builder.OpenElement(109, "rect");
		builder.AddAttribute(110, "x", "23");
		builder.AddAttribute(111, "y", "17");
		builder.AddAttribute(112, "width", "2");
		builder.AddAttribute(113, "height", "6");
		builder.CloseElement();
		builder.OpenElement(114, "rect");
		builder.AddAttribute(115, "x", "23");
		builder.AddAttribute(116, "y", "33");
		builder.AddAttribute(117, "width", "2");
		builder.AddAttribute(118, "height", "6");
		builder.CloseElement();
		builder.OpenElement(119, "rect");
		builder.AddAttribute(120, "x", "27");
		builder.AddAttribute(121, "y", "21");
		builder.AddAttribute(122, "width", "2");
		builder.AddAttribute(123, "height", "6");
		builder.CloseElement();
		builder.OpenElement(124, "rect");
		builder.AddAttribute(125, "x", "39");
		builder.AddAttribute(126, "y", "33");
		builder.AddAttribute(127, "width", "2");
		builder.AddAttribute(128, "height", "6");
		builder.CloseElement();
		builder.OpenElement(129, "rect");
		builder.AddAttribute(130, "x", "39");
		builder.AddAttribute(131, "y", "17");
		builder.AddAttribute(132, "width", "2");
		builder.AddAttribute(133, "height", "6");
		builder.CloseElement();
		builder.OpenElement(134, "rect");
		builder.AddAttribute(135, "x", "39");
		builder.AddAttribute(136, "y", "25");
		builder.AddAttribute(137, "width", "2");
		builder.AddAttribute(138, "height", "6");
		builder.CloseElement();
		builder.OpenElement(139, "path");
		builder.AddAttribute(140, "d", "M39,6.1V7h1.6C40.2,6.6,39.6,6.3,39,6.1z");
		builder.CloseElement();
		builder.OpenElement(141, "rect");
		builder.AddAttribute(142, "x", "31");
		builder.AddAttribute(143, "y", "17");
		builder.AddAttribute(144, "width", "2");
		builder.AddAttribute(145, "height", "6");
		builder.CloseElement();
		builder.OpenElement(146, "path");
		builder.AddAttribute(147, "d", "M40.6,41H39v0.9C39.6,41.7,40.2,41.4,40.6,41z");
		builder.CloseElement();
		builder.OpenElement(148, "rect");
		builder.AddAttribute(149, "x", "35");
		builder.AddAttribute(150, "y", "13");
		builder.AddAttribute(151, "width", "2");
		builder.AddAttribute(152, "height", "6");
		builder.CloseElement();
		builder.OpenElement(153, "rect");
		builder.AddAttribute(154, "x", "31");
		builder.AddAttribute(155, "y", "33");
		builder.AddAttribute(156, "width", "2");
		builder.AddAttribute(157, "height", "6");
		builder.CloseElement();
		builder.OpenElement(158, "rect");
		builder.AddAttribute(159, "x", "35");
		builder.AddAttribute(160, "y", "29");
		builder.AddAttribute(161, "width", "2");
		builder.AddAttribute(162, "height", "6");
		builder.CloseElement();
		builder.OpenElement(163, "rect");
		builder.AddAttribute(164, "x", "39");
		builder.AddAttribute(165, "y", "9");
		builder.AddAttribute(166, "width", "2");
		builder.AddAttribute(167, "height", "6");
		builder.CloseElement();
		builder.OpenElement(168, "rect");
		builder.AddAttribute(169, "x", "35");
		builder.AddAttribute(170, "y", "21");
		builder.AddAttribute(171, "width", "2");
		builder.AddAttribute(172, "height", "6");
		builder.CloseElement();
		builder.OpenElement(173, "rect");
		builder.AddAttribute(174, "x", "31");
		builder.AddAttribute(175, "y", "25");
		builder.AddAttribute(176, "width", "2");
		builder.AddAttribute(177, "height", "6");
		builder.CloseElement();
		builder.OpenElement(178, "rect");
		builder.AddAttribute(179, "x", "35");
		builder.AddAttribute(180, "y", "37");
		builder.AddAttribute(181, "width", "2");
		builder.AddAttribute(182, "height", "5");
		builder.CloseElement();
		builder.OpenElement(183, "rect");
		builder.AddAttribute(184, "x", "35");
		builder.AddAttribute(185, "y", "6");
		builder.AddAttribute(186, "width", "2");
		builder.AddAttribute(187, "height", "5");
		builder.CloseElement();
		builder.OpenElement(188, "rect");
		builder.AddAttribute(189, "x", "31");
		builder.AddAttribute(190, "y", "41");
		builder.AddAttribute(191, "width", "2");
		builder.AddAttribute(192, "height", "1");
		builder.CloseElement();
		builder.OpenElement(193, "rect");
		builder.AddAttribute(194, "x", "23");
		builder.AddAttribute(195, "y", "41");
		builder.AddAttribute(196, "width", "2");
		builder.AddAttribute(197, "height", "1");
		builder.CloseElement();
		builder.OpenElement(198, "rect");
		builder.AddAttribute(199, "x", "27");
		builder.AddAttribute(200, "y", "37");
		builder.AddAttribute(201, "width", "2");
		builder.AddAttribute(202, "height", "5");
		builder.CloseElement();
		builder.OpenElement(203, "rect");
		builder.AddAttribute(204, "x", "19");
		builder.AddAttribute(205, "y", "37");
		builder.AddAttribute(206, "width", "2");
		builder.AddAttribute(207, "height", "5");
		builder.CloseElement();
		builder.OpenElement(208, "rect");
		builder.AddAttribute(209, "x", "7");
		builder.AddAttribute(210, "y", "17");
		builder.AddAttribute(211, "width", "2");
		builder.AddAttribute(212, "height", "6");
		builder.CloseElement();
		builder.OpenElement(213, "path");
		builder.AddAttribute(214, "d", "M9,41H7.4c0.5,0.4,1,0.7,1.6,0.9V41z");
		builder.CloseElement();
		builder.OpenElement(215, "path");
		builder.AddAttribute(216, "d", "M7.4,7H9V6.1C8.4,6.3,7.8,6.6,7.4,7z");
		builder.CloseElement();
		builder.OpenElement(217, "rect");
		builder.AddAttribute(218, "x", "7");
		builder.AddAttribute(219, "y", "33");
		builder.AddAttribute(220, "width", "2");
		builder.AddAttribute(221, "height", "6");
		builder.CloseElement();
		builder.OpenElement(222, "rect");
		builder.AddAttribute(223, "x", "7");
		builder.AddAttribute(224, "y", "25");
		builder.AddAttribute(225, "width", "2");
		builder.AddAttribute(226, "height", "6");
		builder.CloseElement();
		builder.OpenElement(227, "rect");
		builder.AddAttribute(228, "x", "7");
		builder.AddAttribute(229, "y", "9");
		builder.AddAttribute(230, "width", "2");
		builder.AddAttribute(231, "height", "6");
		builder.CloseElement();
		builder.OpenElement(232, "rect");
		builder.AddAttribute(233, "x", "11");
		builder.AddAttribute(234, "y", "29");
		builder.AddAttribute(235, "width", "2");
		builder.AddAttribute(236, "height", "6");
		builder.CloseElement();
		builder.OpenElement(237, "rect");
		builder.AddAttribute(238, "x", "15");
		builder.AddAttribute(239, "y", "17");
		builder.AddAttribute(240, "width", "2");
		builder.AddAttribute(241, "height", "6");
		builder.CloseElement();
		builder.OpenElement(242, "rect");
		builder.AddAttribute(243, "x", "15");
		builder.AddAttribute(244, "y", "33");
		builder.AddAttribute(245, "width", "2");
		builder.AddAttribute(246, "height", "6");
		builder.CloseElement();
		builder.OpenElement(247, "rect");
		builder.AddAttribute(248, "x", "15");
		builder.AddAttribute(249, "y", "9");
		builder.AddAttribute(250, "width", "2");
		builder.AddAttribute(251, "height", "6");
		builder.CloseElement();
		builder.OpenElement(252, "rect");
		builder.AddAttribute(253, "x", "15");
		builder.AddAttribute(254, "y", "6");
		builder.AddAttribute(255, "width", "2");
		builder.AddAttribute(256, "height", "1");
		builder.CloseElement();
		builder.OpenElement(257, "rect");
		builder.AddAttribute(258, "x", "19");
		builder.AddAttribute(259, "y", "6");
		builder.AddAttribute(260, "width", "2");
		builder.AddAttribute(261, "height", "5");
		builder.CloseElement();
		builder.OpenElement(262, "rect");
		builder.AddAttribute(263, "x", "15");
		builder.AddAttribute(264, "y", "25");
		builder.AddAttribute(265, "width", "2");
		builder.AddAttribute(266, "height", "6");
		builder.CloseElement();
		builder.OpenElement(267, "rect");
		builder.AddAttribute(268, "x", "15");
		builder.AddAttribute(269, "y", "41");
		builder.AddAttribute(270, "width", "2");
		builder.AddAttribute(271, "height", "1");
		builder.CloseElement();
		builder.OpenElement(272, "rect");
		builder.AddAttribute(273, "x", "11");
		builder.AddAttribute(274, "y", "21");
		builder.AddAttribute(275, "width", "2");
		builder.AddAttribute(276, "height", "6");
		builder.CloseElement();
		builder.OpenElement(277, "rect");
		builder.AddAttribute(278, "x", "11");
		builder.AddAttribute(279, "y", "6");
		builder.AddAttribute(280, "width", "2");
		builder.AddAttribute(281, "height", "5");
		builder.CloseElement();
		builder.OpenElement(282, "rect");
		builder.AddAttribute(283, "x", "11");
		builder.AddAttribute(284, "y", "37");
		builder.AddAttribute(285, "width", "2");
		builder.AddAttribute(286, "height", "5");
		builder.CloseElement();
		builder.OpenElement(287, "rect");
		builder.AddAttribute(288, "x", "19");
		builder.AddAttribute(289, "y", "13");
		builder.AddAttribute(290, "width", "2");
		builder.AddAttribute(291, "height", "6");
		builder.CloseElement();
		builder.OpenElement(292, "rect");
		builder.AddAttribute(293, "x", "11");
		builder.AddAttribute(294, "y", "13");
		builder.AddAttribute(295, "width", "2");
		builder.AddAttribute(296, "height", "6");
		builder.CloseElement();
		builder.CloseElement();
		builder.CloseElement();
    }
}
